version: '3'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      MONGO_INITDB_DATABASE: COURSES
    ports:
      - "27017:27017"
    networks:
      - backend-network

  backend:
    image: adisharma45/springboot-mongodb:1.0
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_DATABASE=COURSES
      - SPRING_DATA_MONGODB_HOST=mongodb-container
      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - backend-network

  frontend:
    image: adisharma45/frontend:latest
    container_name: react-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend-container:8080
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
